apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: dao-2048
  name: dao-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dao-2048
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: dao-2048
    spec:
      containers:
      - image: daocloud.io/daocloud/dao-2048
        name: dao-2048
        resources: {}
status: {}
