apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: dao-2048
  name: dao-2048
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: dao-2048
status:
  loadBalancer: {}
